// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB2M064uB1f27_bvSY8FvFxImBO2_qcr4',
    appId: '1:1054993111549:web:e8ca2b8bc731342e7be194',
    messagingSenderId: '1054993111549',
    projectId: 'kavach-be141',
    authDomain: 'kavach-be141.firebaseapp.com',
    storageBucket: 'kavach-be141.appspot.com',
    measurementId: 'G-F83E6W800Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwtO7K6fVdIuGaOpsao1Nlq63eqqY3phA',
    appId: '1:1054993111549:android:425c199c616d08717be194',
    messagingSenderId: '1054993111549',
    projectId: 'kavach-be141',
    storageBucket: 'kavach-be141.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAoekfXDjUqlm_wcANLSOTvV9tsEXk-NE',
    appId: '1:1054993111549:ios:aa4893c2cc4cc9527be194',
    messagingSenderId: '1054993111549',
    projectId: 'kavach-be141',
    storageBucket: 'kavach-be141.appspot.com',
    iosClientId:
        '1054993111549-k46cqnbo18v1ta57h16818uo1tevnl72.apps.googleusercontent.com',
    iosBundleId: 'com.example.kavach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAoekfXDjUqlm_wcANLSOTvV9tsEXk-NE',
    appId: '1:1054993111549:ios:aa4893c2cc4cc9527be194',
    messagingSenderId: '1054993111549',
    projectId: 'kavach-be141',
    storageBucket: 'kavach-be141.appspot.com',
    iosClientId:
        '1054993111549-k46cqnbo18v1ta57h16818uo1tevnl72.apps.googleusercontent.com',
    iosBundleId: 'com.example.kavach',
  );
}
